production:
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  adapter: postgresql
  encoding: unicode
  reconnect: false
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: quiz_development
  pool: 5
  username: postgres
  password: athukuthubale8
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: quiz_test
  pool: 5
  username: postgres
  password: athukuthubale8
  host: localhost
  port: 5432

